/**
 * IOF DevTools - SDK generation commands
 *
 * Commands:
 *   iof sdk generate --lang <language> [--output <dir>]
 *   iof sdk update <dir>
 */

import * as fs from "fs";
import * as path from "path";
import type { Command } from "commander";
import chalk from "chalk";
import ora from "ora";
import { loadConfig, requireAuth } from "../config.js";
import { callApi } from "../http.js";

// ── Types ─────────────────────────────────────────────────────────────────────

type SdkLanguage = "typescript" | "python" | "java" | "go" | "all";

const VALID_LANGUAGES: ReadonlySet<string> = new Set([
  "typescript",
  "python",
  "java",
  "go",
  "all",
]);

interface OpenApiSpec {
  openapi: string;
  info: { title: string; version: string };
  paths: Record<string, unknown>;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function assertLanguage(lang: string): asserts lang is SdkLanguage {
  if (!VALID_LANGUAGES.has(lang.toLowerCase())) {
    console.error(
      chalk.red(
        `Invalid language "${lang}". Valid: ${[...VALID_LANGUAGES].join(", ")}`,
      ),
    );
    process.exit(1);
  }
}

function assertOutputDir(outputDir: string): string {
  const resolved = path.resolve(outputDir);
  if (!fs.existsSync(resolved)) {
    fs.mkdirSync(resolved, { recursive: true });
  } else {
    const stat = fs.statSync(resolved);
    if (!stat.isDirectory()) {
      console.error(
        chalk.red(`Output path exists but is not a directory: ${resolved}`),
      );
      process.exit(1);
    }
  }
  return resolved;
}

function writeTypeScriptSdk(outputDir: string, spec: OpenApiSpec): void {
  const clientCode = `/**
 * IOF Platform TypeScript SDK
 * Auto-generated by iof-devtools — DO NOT EDIT MANUALLY
 * API Version: ${spec.info.version}
 * Generated: ${new Date().toISOString()}
 */

export interface ApiClientConfig {
  apiKey: string;
  baseUrl?: string;
  timeout?: number;
}

export class IofApiClient {
  private readonly baseUrl: string;
  private readonly apiKey: string;
  private readonly timeout: number;

  constructor(config: ApiClientConfig) {
    if (!config.apiKey || config.apiKey.length === 0) {
      throw new Error('apiKey is required');
    }
    this.apiKey = config.apiKey;
    this.baseUrl = config.baseUrl ?? 'https://api.islamicopenfinance.com';
    this.timeout = config.timeout ?? 30000;
  }

  private async request<T>(method: string, path: string, body?: unknown): Promise<T> {
    const url = \`\${this.baseUrl}\${path}\`;
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeout);

    try {
      const response = await fetch(url, {
        method,
        headers: {
          'Authorization': \`Bearer \${this.apiKey}\`,
          'Content-Type': 'application/json',
          'User-Agent': 'iof-sdk-typescript/1.0.0',
        },
        body: body !== undefined ? JSON.stringify(body) : undefined,
        signal: controller.signal,
      });

      if (!response.ok) {
        const errorBody = await response.json().catch(() => ({})) as { error?: { code?: string; message?: string } };
        throw new Error(\`[\${errorBody?.error?.code ?? 'API_ERROR'}] \${errorBody?.error?.message ?? response.statusText}\`);
      }

      return response.json() as Promise<T>;
    } finally {
      clearTimeout(timer);
    }
  }

  // ── Contracts ──────────────────────────────────────────────────────────────

  async createContract(type: string, data: Record<string, unknown>): Promise<unknown> {
    return this.request('POST', \`/api/v1/contracts/\${type}\`, data);
  }

  async listContracts(params?: { status?: string; type?: string; page?: number; limit?: number }): Promise<unknown> {
    const qs = new URLSearchParams();
    if (params?.status) qs.set('status', params.status);
    if (params?.type) qs.set('type', params.type);
    if (params?.page) qs.set('page', String(params.page));
    if (params?.limit) qs.set('limit', String(params.limit));
    return this.request('GET', \`/api/v1/contracts?\${qs.toString()}\`);
  }

  async getContract(id: string): Promise<unknown> {
    if (!id || id.length === 0) throw new Error('Contract ID is required');
    return this.request('GET', \`/api/v1/contracts/\${id}\`);
  }

  // ── Shariah ───────────────────────────────────────────────────────────────

  async validateShariah(contract: unknown): Promise<unknown> {
    return this.request('POST', '/api/v1/shariah/validate', { contract });
  }

  async listShariahRules(category?: string): Promise<unknown> {
    const qs = category ? \`?category=\${category}\` : '';
    return this.request('GET', \`/api/v1/shariah/rules\${qs}\`);
  }

  // ── Auth ──────────────────────────────────────────────────────────────────

  async whoami(): Promise<unknown> {
    return this.request('GET', '/api/v1/auth/me');
  }
}

export default IofApiClient;
`;

  fs.writeFileSync(path.join(outputDir, "client.ts"), clientCode, "utf-8");

  const packageJson = {
    name: "@iof/sdk-typescript",
    version: spec.info.version,
    description: "IOF Platform TypeScript SDK",
    main: "dist/client.js",
    types: "dist/client.d.ts",
    scripts: { build: "tsc", prepublishOnly: "npm run build" },
    license: "Apache-2.0",
  };
  fs.writeFileSync(
    path.join(outputDir, "package.json"),
    JSON.stringify(packageJson, null, 2),
    "utf-8",
  );

  const readme = `# IOF TypeScript SDK\n\nAuto-generated from the IOF OpenAPI specification.\n\n## Installation\n\n\`\`\`bash\nnpm install @iof/sdk-typescript\n\`\`\`\n\n## Usage\n\n\`\`\`typescript\nimport { IofApiClient } from '@iof/sdk-typescript';\n\nconst client = new IofApiClient({ apiKey: process.env.IOF_API_KEY! });\nconst contracts = await client.listContracts({ status: 'ACTIVE' });\n\`\`\`\n`;
  fs.writeFileSync(path.join(outputDir, "README.md"), readme, "utf-8");
}

function writePythonSdk(outputDir: string, spec: OpenApiSpec): void {
  const clientCode = `"""
IOF Platform Python SDK
Auto-generated by iof-devtools — DO NOT EDIT MANUALLY
API Version: ${spec.info.version}
Generated: ${new Date().toISOString()}
"""

from __future__ import annotations
import json
import urllib.request
import urllib.error
from typing import Any, Dict, Optional


class IofApiClient:
    def __init__(self, api_key: str, base_url: str = "https://api.islamicopenfinance.com", timeout: int = 30):
        if not api_key:
            raise ValueError("api_key is required")
        self._api_key = api_key
        self._base_url = base_url.rstrip("/")
        self._timeout = timeout

    def _request(self, method: str, path: str, body: Optional[Dict[str, Any]] = None) -> Any:
        url = f"{self._base_url}{path}"
        data = json.dumps(body).encode("utf-8") if body else None
        req = urllib.request.Request(
            url, data=data, method=method,
            headers={
                "Authorization": f"Bearer {self._api_key}",
                "Content-Type": "application/json",
                "User-Agent": "iof-sdk-python/1.0.0",
            },
        )
        try:
            with urllib.request.urlopen(req, timeout=self._timeout) as resp:
                return json.loads(resp.read().decode("utf-8"))
        except urllib.error.HTTPError as e:
            body = json.loads(e.read().decode("utf-8")) if e.fp else {}
            err = body.get("error", {})
            raise RuntimeError(f"[{err.get('code', 'API_ERROR')}] {err.get('message', str(e))}") from e

    def create_contract(self, contract_type: str, data: Dict[str, Any]) -> Any:
        return self._request("POST", f"/api/v1/contracts/{contract_type}", data)

    def list_contracts(self, status: Optional[str] = None, contract_type: Optional[str] = None) -> Any:
        params = []
        if status: params.append(f"status={status}")
        if contract_type: params.append(f"type={contract_type}")
        qs = "?" + "&".join(params) if params else ""
        return self._request("GET", f"/api/v1/contracts{qs}")

    def get_contract(self, contract_id: str) -> Any:
        if not contract_id:
            raise ValueError("contract_id is required")
        return self._request("GET", f"/api/v1/contracts/{contract_id}")

    def validate_shariah(self, contract: Dict[str, Any]) -> Any:
        return self._request("POST", "/api/v1/shariah/validate", {"contract": contract})

    def whoami(self) -> Any:
        return self._request("GET", "/api/v1/auth/me")
`;
  fs.writeFileSync(path.join(outputDir, "client.py"), clientCode, "utf-8");
  fs.writeFileSync(
    path.join(outputDir, "README.md"),
    `# IOF Python SDK\n\nAuto-generated SDK for the IOF Platform.\n\n## Usage\n\n\`\`\`python\nfrom client import IofApiClient\nclient = IofApiClient(api_key=os.environ["IOF_API_KEY"])\nprint(client.list_contracts())\n\`\`\`\n`,
    "utf-8",
  );
}

// ── Command registration ──────────────────────────────────────────────────────

export function registerSdkCommands(program: Command): void {
  const sdkCmd = program
    .command("sdk")
    .description("Generate and update client SDKs");

  // iof sdk generate
  sdkCmd
    .command("generate")
    .description("Generate a client SDK from the IOF OpenAPI spec")
    .requiredOption(
      "--lang <language>",
      "Target language: typescript|python|java|go|all",
    )
    .option("--output <dir>", "Output directory", "./sdk")
    .action(async (opts: { lang: string; output: string }) => {
      assertLanguage(opts.lang);
      const config = loadConfig();
      requireAuth(config);

      const languages: SdkLanguage[] =
        opts.lang === "all"
          ? ["typescript", "python", "java", "go"]
          : [opts.lang as SdkLanguage];

      const outputBase = assertOutputDir(opts.output);

      const spinner = ora("Fetching OpenAPI specification...").start();

      let spec: OpenApiSpec;
      try {
        const response = await callApi<OpenApiSpec>(
          config,
          "GET",
          "/api/v1/openapi.json",
        );
        spec = response.data;
        spinner.succeed("OpenAPI spec fetched.");
      } catch {
        // Fall back to a minimal stub spec for offline/sandbox usage
        spinner.warn(
          "Could not fetch live OpenAPI spec — using built-in stub.",
        );
        spec = {
          openapi: "3.0.3",
          info: { title: "IOF Platform API", version: "1.0.0" },
          paths: {},
        };
      }

      const maxLangs = Math.min(languages.length, 4);
      for (let i = 0; i < maxLangs; i++) {
        const lang = languages[i];
        if (!lang) {
          continue;
        }

        const langDir =
          opts.lang === "all" ? path.join(outputBase, lang) : outputBase;
        assertOutputDir(langDir);

        const langSpinner = ora(`Generating ${lang} SDK → ${langDir}`).start();

        try {
          switch (lang) {
            case "typescript":
              writeTypeScriptSdk(langDir, spec);
              break;
            case "python":
              writePythonSdk(langDir, spec);
              break;
            case "java":
            case "go":
              // Placeholder for Java/Go — would invoke openapi-generator or similar
              fs.writeFileSync(
                path.join(langDir, "README.md"),
                `# IOF ${lang.charAt(0).toUpperCase() + lang.slice(1)} SDK\n\nGeneration requires \`openapi-generator-cli\` for this language.\n\nRun:\n\`\`\`bash\nnpx @openapitools/openapi-generator-cli generate -i openapi.json -g ${lang} -o .\n\`\`\`\n`,
                "utf-8",
              );
              break;
          }
          langSpinner.succeed(`${lang} SDK generated → ${langDir}`);
        } catch (err) {
          langSpinner.fail(`Failed to generate ${lang} SDK.`);
          const e = err as Error;
          console.error(chalk.red(e.message));
        }
      }

      console.log(`\n${chalk.green("✓")} SDK generation complete.`);
      if (opts.lang !== "all") {
        console.log(`  Output: ${chalk.cyan(outputBase)}`);
      }
    });

  // iof sdk update
  sdkCmd
    .command("update <dir>")
    .description("Re-generate an existing SDK in the specified directory")
    .action(async (dir: string) => {
      const resolved = path.resolve(dir);
      if (!fs.existsSync(resolved)) {
        console.error(chalk.red(`Directory not found: ${resolved}`));
        process.exit(1);
      }

      // Detect language from existing files
      let detectedLang: SdkLanguage | null = null;
      if (fs.existsSync(path.join(resolved, "client.ts"))) {
        detectedLang = "typescript";
      } else if (fs.existsSync(path.join(resolved, "client.py"))) {
        detectedLang = "python";
      }

      if (!detectedLang) {
        console.error(
          chalk.red(
            `Could not detect SDK language in ${resolved}. Supported: TypeScript (client.ts), Python (client.py)`,
          ),
        );
        process.exit(1);
      }

      console.log(
        `${chalk.blue("ℹ")} Detected ${detectedLang} SDK in ${resolved}`,
      );
      console.log(`Re-generating...`);

      const config = loadConfig();
      requireAuth(config);

      const spinner = ora("Fetching OpenAPI specification...").start();
      let spec: OpenApiSpec;
      try {
        const response = await callApi<OpenApiSpec>(
          config,
          "GET",
          "/api/v1/openapi.json",
        );
        spec = response.data;
        spinner.succeed("OpenAPI spec fetched.");
      } catch {
        spinner.warn("Could not fetch live spec — using built-in stub.");
        spec = {
          openapi: "3.0.3",
          info: { title: "IOF Platform API", version: "1.0.0" },
          paths: {},
        };
      }

      if (detectedLang === "typescript") {
        writeTypeScriptSdk(resolved, spec);
      } else if (detectedLang === "python") {
        writePythonSdk(resolved, spec);
      }

      console.log(`${chalk.green("✓")} SDK updated: ${resolved}`);
    });
}
